### PR TITLE
Syntax highlighting and autocomplete

### PR DESCRIPTION
**Pull request by guytish**

### CODE REVIEW

**Comment by Allendar** [comment]
I'm not really specialized in writing these, but it would be amazing to have this for SublimeText and Atom too.

**Comment by viaguyt** [comment]
Check this out for SublimeText 3:
https://github.com/valyala/quicktemplate/issues/19

**Comment by Allendar** [comment]
Very nice. I mainly use Atom. I'll try to look into it more soon.

**Comment by Allendar** [comment]
I'm trying to start this older package for now https://github.com/stereosteve/language-quicktemplate . Maybe we can expand on that.

**Comment by guytish** [comment]
@Allendar - LGTM

**Comment by valyala** [comment]
Thanks for the contribution!

**Pull request merged**
